version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: my_movie_list
      POSTGRES_PASSWORD: my_movie_list
      POSTGRES_DB: my_movie_list_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
